stages:
  - quality-checks
  - release


app-lint-server:
  image: containers-registry.stackroute.in/enterprisecommon/container_mirror/python:3.8-slim
  stage: quality-checks
  script:
    - pip install -r requirements.txt
    - pylint src common --rcfile=./lintrules.rc
  only:
    - /^feature_*/
    - /^release_*/
    - /^patch_*/


app-test-server:
  image: containers-registry.stackroute.in/enterprisecommon/container_mirror/python:3.8-slim
  stage: quality-checks
  services:
    - name: containers-registry.stackroute.in/enterprisecommon/container_mirror/mongo:3.6
      alias: mongodb
  variables:
    # Mongo url to be used in testing
    MONGO_TEST_URL: "mongodb://mongodb:27017/sampleDB"
  script:
    - pip install -r requirements.txt
    - python -m pytest
  only:
    - /^feature_*/
    - /^release_*/
    - /^patch_*/


#include:
#  - local: '/ci_includes/.gitlab-cd-dev.yml'
  # - local: '/ci_includes/.gitlab-cd-prod.yml'
 
